work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: ${EXP_NAME:gpt_oss_20b}
workspace: ./output

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml

    # model to run
    model: ${PRIMUS_MODEL:gpt_oss_20B}.yaml
    overrides:
      # log
      wandb_project: "Primus_DeepSeek_Pretrain"
      stderr_sink_level: DEBUG
      log_interval: 99999999  # Suppress console logs

      # debug
      moe_router_force_load_balancing: true
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50

      # profile
      profile: false
      use_pytorch_profiler: false
      profile_step_end: 7
      profile_step_start: 6

      # precision (mixed precision training)
      bf16: true
      fp16: false
      fp8: null  # Set to "e4m3" or "hybrid" for FP8 training

      # hyper parameters
      train_iters: ${PRIMUS_TRAIN_ITERS:20}
      micro_batch_size: ${PRIMUS_MICRO_BATCH_SIZE:4}
      global_batch_size: ${PRIMUS_GLOBAL_BATCH_SIZE:640}
      seq_length: ${PRIMUS_SEQ_LENGTH:8192}
      max_position_embeddings: ${PRIMUS_MAX_POSITION_EMBEDDINGS:8192}
      lr: ${PRIMUS_LR:1.0e-5}
      min_lr: 1.0e-5  # Set to 10% of max LR like Llama 8B (8e-5 is 10% of 8e-4)
      lr_warmup_iters: ${PRIMUS_LR_WARMUP_ITERS:128}  # Match Llama 8B warmup
      lr_decay_iters: 1199872  # Match Llama 8B decay schedule (75M samples / 640 GBS = 117187 iters, but using their value)
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: ${PRIMUS_TP:1}
      pipeline_model_parallel_size: ${PRIMUS_PP:1}
      expert_model_parallel_size: ${PRIMUS_EP:8}
      overlap_grad_reduce: true
      overlap_param_gather: true

      # data
      mock_data: false
      train_data_path: "10 /data/c4-train.en_6_text_document"
      valid_data_path: "/data/c4-validation-91205-samples.en_text_document"
      test_data_path: "/data/c4-validation-91205-samples.en_text_document"

      # fusion
      # 20250321: need latest megatron docker image
      moe_permute_fusion: false
      # fused wgrad gemm and accumulation
      gradient_accumulation_fusion: false
      # recommend set `false` in fp8
      moe_use_legacy_grouped_gemm: true
      # fused topk router with aux score
      moe_use_fused_router_with_aux_score: false
      # MLA
      multi_latent_attention: false
      # rope fusion
      apply_rope_fusion: false

      # DeepEP does not support moe_shared_expert_overlap
      moe_shared_expert_overlap: false
      # DeepEP only supports float32 probs
      moe_router_dtype: fp32

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true
      exit_on_missing_checkpoint: false
      ckpt_format: torch
      eval_iters: 64  # 64 iters × 2 MBS × 8 GPUs = 1024 eval samples (matching Llama 8B)
      eval_interval: ${PRIMUS_EVAL_INTERVAL:5}

      # Turbo
      enable_primus_turbo: true
      use_turbo_attention: true
      use_turbo_grouped_mlp: true

      # deepep
      use_turbo_deepep: true

      # 64 or 80 for ep8, 32 for ep16-64 is best practice
      turbo_deepep_num_cu: 64
      turbo_deepep_use_comm_stream: false

      # sync-free moe support stage 0-3, 0 means not use sync-free moe
      # stage 3 is completely no gpu-cpu sync in MoE, but cost more memory
      # stage 2 is recommended for better performance
      turbo_sync_free_moe_stage: 2

      # Cross entropy flags
      # cross_entropy_fusion_impl: "te"
      # cross_entropy_loss_fusion: true

