ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:25.12-py3
FROM ${BASE_IMAGE}

WORKDIR /workspace

RUN pip install --no-cache-dir \
    pyyaml \
    pybind11 \
    ninja \
    packaging \
    transformers

WORKDIR /workspace/deps
RUN git clone --recursive https://github.com/AMD-AIG-AIMA/Primus.git && \
    cd Primus && \
    git checkout 82723988c2f4b5440f632a1f99eb9c742b7ef97c && \
    git submodule update --init --recursive && \
    pip install -r requirements.txt

WORKDIR /workspace/code/patches
COPY patches/megatron_yarn_rotary_embedding.patch .
RUN cd /workspace/deps/Primus/third_party/Megatron-LM && \
    git apply /workspace/code/patches/megatron_yarn_rotary_embedding.patch && \
    pip install -e . --no-deps

ENV PYTHONPATH="/workspace/deps/Primus:/workspace/deps/Primus/third_party/Megatron-LM"

WORKDIR /workspace/code

COPY . .

# Install primus-mllog from local wheel
RUN pip install primus_mllog-0.1.0-py3-none-any.whl

RUN pip install --no-build-isolation git+https://github.com/fanshiqing/grouped_gemm@v1.1.4
RUN pip install --no-build-isolation git+https://github.com/NVIDIA/mlperf-common.git@b86d175a05849d650a8ff69c1e2c37b9f4e61d51
